#!/bin/bash
#
# rebuild-phase2.sh
# Guided checklist for rebuilding the Phase 2 environment.
#
# This is NOT blind automation -- you should understand each step.
# Use this as a quick reference when rebuilding after a teardown.
# Try to do each step from memory first, then check here if stuck.
#
# Total rebuild time: ~20 minutes
#

echo "============================================="
echo "  Phase 2 Rebuild -- Quick Environment Setup"
echo "============================================="
echo ""
echo "Follow these steps to recreate your Phase 2 environment."
echo "Each step includes the key command and approximate time."
echo ""

echo "============================================="
echo "  Step 1: Create VPC (~1 minute)"
echo "============================================="
echo ""
echo "Use the AWS Console 'VPC and more' wizard:"
echo "  - VPC name: ecommerce-vpc"
echo "  - CIDR: 10.0.0.0/16"
echo "  - 2 public subnets + 2 private subnets"
echo "  - 2 Availability Zones"
echo "  - 1 Internet Gateway"
echo "  - NAT Gateway: None (saves cost)"
echo ""
echo "Or via CLI:"
echo "  aws ec2 create-vpc --cidr-block 10.0.0.0/16"
echo "  # Then create subnets, IGW, and route tables manually"
echo "  # (Console wizard is faster for this)"
echo ""
echo "Save: VPC_ID, SUBNET_IDS"
echo ""

echo "============================================="
echo "  Step 2: Launch EC2 (~2 minutes)"
echo "============================================="
echo ""
echo "Key settings:"
echo "  - AMI: Amazon Linux 2023"
echo "  - Instance type: t2.micro (free tier)"
echo "  - Key pair: your existing key pair"
echo "  - VPC: the one just created"
echo "  - Subnet: public subnet"
echo "  - Auto-assign public IP: Enable"
echo "  - Security group: Create new"
echo "    - SSH (22) from your IP"
echo "    - HTTP (80) from 0.0.0.0/0"
echo "    - HTTPS (443) from 0.0.0.0/0"
echo ""
echo "After launch:"
echo "  - Allocate and associate an Elastic IP"
echo "  - SSH in: ssh -i ~/your-key.pem ec2-user@<elastic-ip>"
echo ""
echo "Save: EC2_ID, EC2_SG_ID, EIP_ALLOC_ID, ELASTIC_IP"
echo ""

echo "============================================="
echo "  Step 3: Install software on EC2 (~3 minutes)"
echo "============================================="
echo ""
echo "  sudo dnf install -y nodejs20 git"
echo "  sudo npm install -g pm2 pnpm"
echo "  sudo dnf install -y nginx"
echo "  sudo systemctl enable nginx && sudo systemctl start nginx"
echo ""

echo "============================================="
echo "  Step 4: Create RDS (~5-10 minutes)"
echo "============================================="
echo ""
echo "4a. Create RDS security group:"
echo "  aws ec2 create-security-group \\"
echo "    --group-name ecommerce-rds-sg \\"
echo "    --description 'RDS PostgreSQL' \\"
echo "    --vpc-id \$VPC_ID"
echo ""
echo "4b. Add inbound rule (SG referencing):"
echo "  aws ec2 authorize-security-group-ingress \\"
echo "    --group-id \$RDS_SG_ID \\"
echo "    --protocol tcp --port 5432 \\"
echo "    --source-group \$EC2_SG_ID"
echo ""
echo "4c. Create DB subnet group:"
echo "  aws rds create-db-subnet-group \\"
echo "    --db-subnet-group-name ecommerce-db-subnet-group \\"
echo "    --db-subnet-group-description 'Private subnets for RDS' \\"
echo "    --subnet-ids \$PRIVATE_SUBNET_1 \$PRIVATE_SUBNET_2"
echo ""
echo "4d. Create RDS instance:"
echo "  aws rds create-db-instance \\"
echo "    --db-instance-identifier ecommerce-db \\"
echo "    --db-instance-class db.t3.micro \\"
echo "    --engine postgres --engine-version 16 \\"
echo "    --master-username postgres --master-user-password '<password>' \\"
echo "    --allocated-storage 20 --storage-type gp2 \\"
echo "    --db-name ecommerce \\"
echo "    --vpc-security-group-ids \$RDS_SG_ID \\"
echo "    --db-subnet-group-name ecommerce-db-subnet-group \\"
echo "    --no-multi-az --no-publicly-accessible \\"
echo "    --backup-retention-period 7 --storage-encrypted \\"
echo "    --no-enable-performance-insights"
echo ""
echo "4e. Wait for RDS:"
echo "  aws rds wait db-instance-available --db-instance-identifier ecommerce-db"
echo ""
echo "Save: RDS_SG_ID, RDS_ENDPOINT"
echo ""

echo "============================================="
echo "  Step 5: Deploy app (~3 minutes)"
echo "============================================="
echo ""
echo "On EC2:"
echo "  cd ~"
echo "  git clone <your-repo-url> app"
echo "  cd app"
echo "  pnpm install"
echo "  pnpm run build:server"
echo "  pnpm run build:client"
echo ""
echo "Set DATABASE_URL in ecosystem.config.js, then:"
echo "  pm2 start ecosystem.config.js"
echo "  pm2 startup    # Follow the printed sudo command"
echo "  pm2 save"
echo ""
echo "Configure Nginx:"
echo "  sudo cp /path/to/ecommerce.conf /etc/nginx/conf.d/"
echo "  sudo nginx -t && sudo systemctl reload nginx"
echo ""

echo "============================================="
echo "  Step 6: Run migrations + seed (~1 minute)"
echo "============================================="
echo ""
echo "  cd ~/app"
echo "  DATABASE_URL=\"postgresql://postgres:<password>@<rds-endpoint>:5432/ecommerce\" pnpm run db:push"
echo "  DATABASE_URL=\"postgresql://postgres:<password>@<rds-endpoint>:5432/ecommerce\" pnpm run seed"
echo "  pm2 restart ecommerce-api"
echo ""

echo "============================================="
echo "  Step 7: Verify (~1 minute)"
echo "============================================="
echo ""
echo "  # Health check"
echo "  curl http://localhost:3000/api/health"
echo ""
echo "  # Products from database"
echo "  curl http://localhost:3000/api/products"
echo ""
echo "  # Through Nginx (from local machine)"
echo "  curl http://<elastic-ip>/api/products"
echo ""
echo "  # Visit in browser"
echo "  open http://<elastic-ip>"
echo ""

echo "============================================="
echo "  Time estimates"
echo "============================================="
echo ""
echo "  Step 1 (VPC):            ~1 minute"
echo "  Step 2 (EC2):            ~2 minutes"
echo "  Step 3 (Install):        ~3 minutes"
echo "  Step 4 (RDS):            ~5-10 minutes (mostly waiting)"
echo "  Step 5 (Deploy):         ~3 minutes"
echo "  Step 6 (Migrate + Seed): ~1 minute"
echo "  Step 7 (Verify):         ~1 minute"
echo "  --------------------------------"
echo "  Total:                   ~16-21 minutes"
echo ""
echo "Tip: Start RDS creation early (Step 4d) while you"
echo "work on Steps 5-6 -- RDS takes 5-10 minutes to launch."
