#!/usr/bin/env bash
#
# teardown-checklist.sh
# Prints a checklist of AWS resources to verify and terminate after each practice session.
# This is a REMINDER script -- it does NOT automatically destroy anything.
#

set -euo pipefail

echo "============================================="
echo "  AWS Resource Teardown Checklist"
echo "============================================="
echo ""
echo "Before closing your practice session, verify"
echo "that the following resources are terminated"
echo "or cleaned up to avoid unexpected charges."
echo ""
echo "--- Compute ---"
echo "[ ] EC2 instances -- Terminate any running instances"
echo "    aws ec2 describe-instances --filters Name=instance-state-name,Values=running"
echo ""
echo "[ ] Elastic IPs -- Release any unattached Elastic IPs"
echo "    aws ec2 describe-addresses"
echo ""
echo "--- Storage ---"
echo "[ ] EBS volumes -- Delete any unattached volumes"
echo "    aws ec2 describe-volumes --filters Name=status,Values=available"
echo ""
echo "[ ] S3 buckets -- Empty and delete practice buckets"
echo "    aws s3 ls"
echo ""
echo "--- Networking ---"
echo "[ ] NAT Gateways -- Delete any NAT Gateways (they cost ~\$0.045/hr)"
echo "    aws ec2 describe-nat-gateways --filter Name=state,Values=available"
echo ""
echo "[ ] Load Balancers -- Delete any ALBs/NLBs"
echo "    aws elbv2 describe-load-balancers"
echo ""
echo "[ ] Custom VPCs -- Delete practice VPCs (and their subnets, route tables, IGWs)"
echo "    aws ec2 describe-vpcs --filters Name=is-default,Values=false"
echo ""
echo "--- Database ---"
echo "[ ] RDS instances -- Delete any practice RDS instances (skip final snapshot)"
echo "    aws rds describe-db-instances"
echo ""
echo "--- Other ---"
echo "[ ] CloudWatch alarms -- Delete practice alarms"
echo "[ ] Route 53 hosted zones -- Check for extra zones beyond your primary domain"
echo "[ ] ECS clusters -- Delete any practice clusters"
echo ""
echo "============================================="
echo "  Tip: Check your AWS Billing dashboard for"
echo "  any unexpected charges after each session."
echo "============================================="
